name: manual_down_deploy_pr
# deploy_host
# deploy_host_username
# deploy_host_password
# Create file in advance: /home/ecs-user/nocobase/pr-docker-compose-template.yml
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'pr number is '
        required: true

jobs:
  up_deploy:
    runs-on: ubuntu-latest
    environment:
      name: test_pr_${{ inputs.pr_number }}
      url: http://${{ secrets.deploy_host }}:1${{ inputs.pr_number }}
    steps:
      - name: ssh up deploy
        uses: appleboy/ssh-action@master
        env:
          pr_number: ${{ inputs.pr_number }}
          pr_compose_dir: pr-${{ inputs.pr_number }}
        with:
          host: ${{ secrets.deploy_host }}
          username: ${{ secrets.deploy_host_username }}
          password: ${{ secrets.deploy_host_password }}
          script: |
            mkdir -p /home/ecs-user/nocobase/${{ env.pr_compose_dir }}
            cp /home/ecs-user/nocobase/pr-docker-compose-template.yml /home/ecs-user/nocobase/${{ env.pr_compose_dir }}/docker-compose.yml
            cd /home/ecs-user/nocobase/${{ env.pr_compose_dir }}
            export pr_number=${{ env.pr_number }}
            sudo docker compose up -d
